#!/bin/bash
# =============================================================================
# VendorBoss API — One-Time Server Setup Script
# Run this ONCE on your Ubuntu server to prepare it for deployments.
#
# Usage:
#   ssh into your server, then:
#   curl -o setup.sh https://raw.githubusercontent.com/YOUR_USERNAME/YOUR_REPO/main/vendorboss-api/scripts/server_setup.sh
#   chmod +x setup.sh && sudo bash setup.sh
#
#   OR copy it over with scp and run it.
# =============================================================================

set -e

APP_USER="vendorboss"
APP_DIR="/opt/vendorboss/api"
VENV="$APP_DIR/venv"
PYTHON="python3"

echo "============================================="
echo " VendorBoss API — Server Setup"
echo "============================================="

# ── 1. System packages ────────────────────────────────────────────────────────
echo ""
echo "📦 Installing system packages..."
apt-get update -qq
apt-get install -y -qq \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    postgresql \
    postgresql-contrib \
    nginx \
    git \
    curl \
    rsync \
    build-essential \
    libpq-dev

# ── 2. Create app user ────────────────────────────────────────────────────────
echo ""
echo "👤 Creating app user..."
if ! id "$APP_USER" &>/dev/null; then
    useradd --system --create-home --shell /bin/bash "$APP_USER"
    echo "   Created user: $APP_USER"
else
    echo "   User $APP_USER already exists"
fi

# ── 3. Create app directory ───────────────────────────────────────────────────
echo ""
echo "📁 Setting up app directory..."
mkdir -p "$APP_DIR"
chown -R "$APP_USER:$APP_USER" /opt/vendorboss

# ── 4. Python virtual environment ────────────────────────────────────────────
echo ""
echo "🐍 Creating Python virtual environment..."
sudo -u "$APP_USER" $PYTHON -m venv "$VENV"
echo "   Venv created at $VENV"

# ── 5. PostgreSQL setup ───────────────────────────────────────────────────────
echo ""
echo "🗄️  Setting up PostgreSQL..."
systemctl start postgresql
systemctl enable postgresql

# Create DB user and database (prompts for password)
echo ""
echo "   ⚠️  You'll be prompted to set a password for the vendorboss database user."
echo "      Save this — you'll need it in your .env file."
echo ""
sudo -u postgres psql <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'vendorboss') THEN
        CREATE ROLE vendorboss WITH LOGIN PASSWORD 'CHANGE_ME_NOW';
    END IF;
END
\$\$;

CREATE DATABASE vendorboss_db OWNER vendorboss;
GRANT ALL PRIVILEGES ON DATABASE vendorboss_db TO vendorboss;
SQL
echo "   ✅ Database 'vendorboss_db' created with user 'vendorboss'"
echo "   ⚠️  Change the password: sudo -u postgres psql -c \"ALTER USER vendorboss PASSWORD 'your-strong-password';\""

# ── 6. Environment file ───────────────────────────────────────────────────────
echo ""
echo "⚙️  Creating .env file..."
if [ ! -f "$APP_DIR/.env" ]; then
    SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    cat > "$APP_DIR/.env" <<ENV
# VendorBoss API — Production Environment
# Generated by server_setup.sh — edit as needed

DATABASE_URL=postgresql://vendorboss:CHANGE_ME_NOW@localhost:5432/vendorboss_db
SECRET_KEY=$SECRET
SCANBOSS_API_KEY=your-scanboss-key-here
PORT=8000
ENVIRONMENT=production
ENV
    chown "$APP_USER:$APP_USER" "$APP_DIR/.env"
    chmod 600 "$APP_DIR/.env"
    echo "   ✅ .env created at $APP_DIR/.env"
    echo "   ⚠️  Edit it now: nano $APP_DIR/.env"
else
    echo "   .env already exists — skipping"
fi

# ── 7. Systemd service ────────────────────────────────────────────────────────
echo ""
echo "⚙️  Installing systemd service..."
cat > /etc/systemd/system/vendorboss.service <<SERVICE
[Unit]
Description=VendorBoss API
After=network.target postgresql.service
Wants=postgresql.service

[Service]
Type=simple
User=$APP_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=$VENV/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=vendorboss

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable vendorboss
echo "   ✅ Service installed and enabled (not started yet — deploy first)"

# ── 8. Nginx reverse proxy ────────────────────────────────────────────────────
echo ""
echo "🌐 Configuring Nginx..."
cat > /etc/nginx/sites-available/vendorboss <<NGINX
server {
    listen 80;
    server_name _;  # Replace with your domain or IP if needed

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/vendorboss /etc/nginx/sites-enabled/vendorboss
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl restart nginx && systemctl enable nginx
echo "   ✅ Nginx configured and running"

# ── 9. Sudoers — allow runner to restart service without password ─────────────
echo ""
echo "🔐 Configuring sudoers for deployment..."
cat > /etc/sudoers.d/vendorboss-deploy <<SUDOERS
# Allow the GitHub Actions runner user to restart the vendorboss service
# The runner will run as the user you register it with (often 'ubuntu' or your login)
%sudo ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart vendorboss
%sudo ALL=(ALL) NOPASSWD: /usr/bin/systemctl status vendorboss
%sudo ALL=(ALL) NOPASSWD: /usr/bin/systemctl is-active vendorboss
SUDOERS
chmod 0440 /etc/sudoers.d/vendorboss-deploy
echo "   ✅ Sudoers configured"

# ── 10. GitHub Actions Runner instructions ────────────────────────────────────
echo ""
echo "============================================="
echo " ✅ Server setup complete!"
echo "============================================="
echo ""
echo "NEXT STEPS:"
echo ""
echo "1. Edit your .env file:"
echo "   nano $APP_DIR/.env"
echo "   (Update DATABASE_URL password and SCANBOSS_API_KEY)"
echo ""
echo "2. Install the GitHub Actions self-hosted runner:"
echo "   - Go to your GitHub repo"
echo "   - Settings → Actions → Runners → New self-hosted runner"
echo "   - Choose Linux x64"
echo "   - Follow the commands GitHub shows you"
echo "   - When asked for labels, just press Enter (default is fine)"
echo "   - Install as a service: sudo ./svc.sh install && sudo ./svc.sh start"
echo ""
echo "3. Push to main to trigger your first deployment!"
echo ""
echo "4. Check logs anytime:"
echo "   journalctl -u vendorboss -f"
echo ""
